### ISSUE TITLE
网速显示不完整

### ISSUE THREAD

**Issue by PANCAKE-11** [zou-z/NetSpeed#4]
win10版本22H2 19045.2364
![image](https://user-images.githubusercontent.com/57341071/208402597-661d57a5-9a5f-4751-91c8-267151c21a72.png)

**Comment by zou-z** [comment]
一直显示不全吗，还是在数字比较短的时候能显示全，win10版本21H2 19044.2364是正常的

**Comment by PANCAKE-11** [comment]
一直不全
![Snipaste_2022-12-28_11-57-38](https://user-images.githubusercontent.com/57341071/209755114-19efa63d-9b7a-4bd4-9397-4969730cdefa.png)
![Snipaste_2022-12-28_11-58-00](https://user-images.githubusercontent.com/57341071/209755118-5979ca00-b69c-4697-bafc-f355e36f452a.png)
![Snipaste_2022-12-28_11-58-09](https://user-images.githubusercontent.com/57341071/209755124-57fcb0b9-c550-4e7c-ae5a-1f6f5a754490.png)

**Comment by zou-z** [comment]
![image](https://user-images.githubusercontent.com/45748083/209894198-4409c204-acc5-4bba-94ef-8abd2a6e69ab.png)
我今天系统升级到了22H2 19045.2364是可以的，看看你设置里面屏幕的分辨率是不是1920*1080，缩放是不是100%

**Comment by PANCAKE-11** [comment]
好吧 我改成100%后重启电脑显示完整了  不过我用的是笔记本屏幕比较小必须得缩放一下

**Comment by zou-z** [comment]
你正常使用时笔记本屏幕分辨率和缩放数值是多少，周末我找个时间修复下

**Comment by PANCAKE-11** [comment]
![image](https://user-images.githubusercontent.com/57341071/209931092-2994e953-ad25-4561-8380-fb3c362fbe67.png)

**Comment by zou-z** [comment]
试试这个最新的版本[NetSpeed_v1.3.1.0](https://github.com/zou-z/NetSpeed/releases/download/1.3.1.0/NetSpeed_v1.3.1.0.zip)
先在状态栏右键菜单中关闭实时网速显示，然后卸载旧版，然后重启下文件管理器，然后安装新版本。

**Comment by PANCAKE-11** [comment]
显示完全了   
![image](https://user-images.githubusercontent.com/57341071/211227317-33551d10-bbae-42f1-8255-84270fbd9353.png)

**Comment by zou-z** [comment]
好的
